version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: mi-app-php7.1
    container_name: app_colpetroleum
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
  
  webserver:
    image: nginx:alpine
    container_name: webserver_colpetroleum
    ports:
      - "4050:80"
      - "4051:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
   
